### PR TITLE
feature: Upgrade loader to be compatible with django 1.10

### PR DESCRIPTION
**Pull request by hmleal**
This pull request closes the issues: #261 #256

### CODE REVIEW

**Comment by kakulukia** [comment]
could someone please release this fixed version?

**Comment by gissehel** [comment]
@hmleal , @syrusakbary ,

Has this PR been tested on Django 1.9 ? (I don't have django 1.9 installed and didn't test it)

Based on the assumption that previous code was working with django 1.9, I understand how the `try`/`except` works for both django 1.9 and 1.10, but I don't understand how the `__init__` with then new `engine` param would work in django 1.9 as it would be called with only 2 parameters right ?

And for django 1.10, it seems that the Loader class, renamed here as BaseLoader seems to take `engine` as `__init__` parameter. But `__init__` is never called. I suppose it would be important.

I haven't played with django for literally 10 years, and all my analysis is just based on few code lines I just read, and not tested, so I may say a lot of silly things.

**Comment by kakulukia** [comment]
travis is continuosly testing this repo and only reported problems for Django 1.6 and 1.7 have a look above

**Comment by RigoOnRails** [comment]
So has this version of PyJade been released yet or?

**Comment by im-n1** [comment]
Hey there!
Thank you for fixing this issue, good job man.

IMHO when you fix such major issue please release new version and put in on PyPy. People then don't have to figure out how to install last commit from master git repo via pip.

**Comment by ptrdvds** [comment]
As of now this issue is not fixed with the current version of pyjade
I am trying Django 1.10.6 with pyjade 4.0.0 and the error still exists.

**Comment by hemulin** [comment]
@ptrdvds 
Looked into my virtualenv site-packages folder into the pyjade.ext and it seemed that though I have the pyjade=4.0.0, the relevant line that fixed this issue in the above PR is missing.
Until it would be fixed (@syrusakbary perhaps something is wrong with the pypi shipping?), you can bypass this issue by installing directly from the master branch on github:
`pip install git+https://github.com/syrusakbary/pyjade.git`

**Pull request merged**
